name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ref_name_slug: ${{ steps.ref.outputs.ref_name_slug }}
      default_slug: ${{ steps.ref.outputs.default_slug }}
    steps:
      - id: ref
        env:
          REF_NAME: ${{ github.ref_name }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
            echo "ref_name_slug=${REF_NAME//[^a-zA-Z0-9]/-}"
            echo "default_slug=${DEFAULT_BRANCH//[^a-zA-Z0-9]/-}"
            echo "ref_name_slug=${REF_NAME//[^a-zA-Z0-9]/-}" >> $GITHUB_OUTPUT
            echo "default_slug=${DEFAULT_BRANCH//[^a-zA-Z0-9]/-}" >> $GITHUB_OUTPUT

  build:
    name: Build Images
    uses: hulkag/infra-workflows/.github/workflows/workflow-docker-build-push.yml@main
    needs: [ prepare ]
    with:
      app_name: ${{ vars.APP_NAME }}
      repository: europe-west3-docker.pkg.dev/ds-base/docker/digistore24-mcp-server
      docker_push: true
      dockerfile: Dockerfile
      target: prod
      tag_config: |
        type=ref,event=pr,prefix=pr-
        type=ref,event=branch,suffix=-{{ sha }}-{{ date 'X' }}
        type=ref,event=tag
      cache_from: |
        type=registry,ref=ghcr.io/${{ github.repository }}/buildcache:${{ needs.prepare.outputs.default_slug }}
        type=registry,ref=ghcr.io/${{ github.repository }}/buildcache:${{ needs.prepare.outputs.ref_name_slug }}
        ${INLINE}
      cache_to: |
        ${{ (startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/tags/')) && format('type=registry,ref=ghcr.io/{0}/buildcache:{1},mode=max', github.repository, needs.prepare.outputs.ref_name_slug) || '' }}
        type=inline
